### ISSUE TITLE
Tooling: Automatic code formatter

### ISSUE THREAD

**Issue by sometimes-i-send-pull-requests** [sbyt32/Preordain#12]
Consider using an automatic code formatter. I recommend [Black](https://github.com/psf/black). YAPF is another option but it can be finicky. There are other options as well. But I recommend Black.

In addition, consider [isort](https://github.com/PyCQA/isort) for sorting imports. This may require some configuration to not conflict with your formatter of choice (isort's default conflicts with Black's default, for example).

**Comment by sbyt32** [comment]
Using Black now, but still need to implement it somehow into my CI pipeline. The formatter is actually very nice, especially for complicated lines with a lot of parens or indentations.

**Comment by sbyt32** [comment]
Using Black w/ args
`black preordain/ tests/ scraper/ --extend-exclude=preordain/static/preordain`

Also in conjunction with pre-commit w/ `trailing-whitespace` & `end-of-file-fixer`
