### ISSUE TITLE
Distribution packaging

### ISSUE THREAD

**Issue by sometimes-i-send-pull-requests** [sbyt32/Preordain#19]
Currently, setup of your project is rather ad-hoc. You have a `requirements.txt`, and expect to have those packages installed. This is OK! Many projects do this. But there is an extra level of polish you can do, if you feel so inclined -- you can turn your project into a bona-fide Python package, such that if you felt like uploading it to PyPI, you could, and anyone could install your project with a single `pip install`.

I'd punt on this for a while, but it's good to have in the back of your mind. You can find the user guide for setuptools here, for when and if you do feel like taking this step: https://setuptools.pypa.io/en/latest/userguide/index.html

**Comment by sbyt32** [comment]
This has been something I've considered here and there, but not sure if putting a package on PyPI would help me with my end goal here.

Right now, I'd consider the project complete when I implement the following things:

- [ ] A front-end to interact with the API (This may be it's own grander project)
- [ ] Decent testing suite.
- [ ] The ability to create backups of the database into a .csv file or other format.
- [ ] Add a collective of cards based on a pre-determined group.
- [ ] Custom Exceptions, Classes, Response/Request Models w/ Pydantic. 
- [x] What I did already

With those things in mind, I'm not sure if making it a package would reach me to those goals. I could be wrong those, and my idea of a package might be different than what it actually is in this context. It might be worth understanding how other packages are structured to better structure my own structure, however.

**Comment by sometimes-i-send-pull-requests** [comment]
Yes, this would not do anything towards those goals. It’s still a nice bit of polish though. Also, I didn’t mean to say you would put this on PyPI, just that it would be in the correct form to put there if you ever did want to. It’s more the fact the structure of such a package is nice, lets you adopt things like setuptools entry points, etc.
